//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let demo = _ModuleRegistry.module("demo");

    Slice.defineSequence(demo, "AudioDataHelper", "Ice.ByteHelper", true);

    demo.VoiceMessageInfo = class
    {
        constructor(sender = "", recipient = "", timestamp = "", duration = 0)
        {
            this.sender = sender;
            this.recipient = recipient;
            this.timestamp = timestamp;
            this.duration = duration;
        }

        _write(ostr)
        {
            ostr.writeString(this.sender);
            ostr.writeString(this.recipient);
            ostr.writeString(this.timestamp);
            ostr.writeInt(this.duration);
        }

        _read(istr)
        {
            this.sender = istr.readString();
            this.recipient = istr.readString();
            this.timestamp = istr.readString();
            this.duration = istr.readInt();
        }

        static get minWireSize()
        {
            return  7;
        }
    };

    Slice.defineStruct(demo.VoiceMessageInfo, true, true);

    const iceC_demo_VoiceChat_ids = [
        "::Ice::Object",
        "::demo::VoiceChat"
    ];

    demo.VoiceChat = class extends Ice.Object
    {
    };

    demo.VoiceChatPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(demo.VoiceChat, demo.VoiceChatPrx, iceC_demo_VoiceChat_ids, 1,
    {
        "sendAudio": [, , , , , [["demo.AudioDataHelper"]], , , , ],
        "sendVoiceMessage": [, , , , [7], [["demo.AudioDataHelper"], [demo.VoiceMessageInfo]], , , , ],
        "initiateCall": [, , , , , [[7]], , , , ],
        "acceptCall": [, , , , , [[7]], , , , ],
        "rejectCall": [, , , , , [[7]], , , , ],
        "endCall": [, , , , , [[7]], , , , ]
    });
    exports.demo = demo;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
