//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public class VoiceMessageInfo implements java.lang.Cloneable,
                                         java.io.Serializable
{
    public String sender;

    public String recipient;

    public String timestamp;

    public int duration;

    public VoiceMessageInfo()
    {
        this.sender = "";
        this.recipient = "";
        this.timestamp = "";
    }

    public VoiceMessageInfo(String sender, String recipient, String timestamp, int duration)
    {
        this.sender = sender;
        this.recipient = recipient;
        this.timestamp = timestamp;
        this.duration = duration;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        VoiceMessageInfo r = null;
        if(rhs instanceof VoiceMessageInfo)
        {
            r = (VoiceMessageInfo)rhs;
        }

        if(r != null)
        {
            if(this.sender != r.sender)
            {
                if(this.sender == null || r.sender == null || !this.sender.equals(r.sender))
                {
                    return false;
                }
            }
            if(this.recipient != r.recipient)
            {
                if(this.recipient == null || r.recipient == null || !this.recipient.equals(r.recipient))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }
            if(this.duration != r.duration)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::demo::VoiceMessageInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sender);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, recipient);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, duration);
        return h_;
    }

    public VoiceMessageInfo clone()
    {
        VoiceMessageInfo c = null;
        try
        {
            c = (VoiceMessageInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.sender);
        ostr.writeString(this.recipient);
        ostr.writeString(this.timestamp);
        ostr.writeInt(this.duration);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.sender = istr.readString();
        this.recipient = istr.readString();
        this.timestamp = istr.readString();
        this.duration = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, VoiceMessageInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public VoiceMessageInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        VoiceMessageInfo v = new VoiceMessageInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<VoiceMessageInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, VoiceMessageInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<VoiceMessageInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(VoiceMessageInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final VoiceMessageInfo _nullMarshalValue = new VoiceMessageInfo();

    /** @hidden */
    public static final long serialVersionUID = 1985943963L;
}
