//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public interface VoiceChatPrx extends com.zeroc.Ice.ObjectPrx
{
    default void sendAudio(byte[] data)
    {
        sendAudio(data, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendAudio(byte[] data, java.util.Map<String, String> context)
    {
        _iceI_sendAudioAsync(data, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioAsync(byte[] data)
    {
        return _iceI_sendAudioAsync(data, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendAudioAsync(byte[] data, java.util.Map<String, String> context)
    {
        return _iceI_sendAudioAsync(data, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendAudioAsync(byte[] iceP_data, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendAudio", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeByteSeq(iceP_data);
                 }, null);
        return f;
    }

    default String sendVoiceMessage(byte[] data, VoiceMessageInfo info)
    {
        return sendVoiceMessage(data, info, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String sendVoiceMessage(byte[] data, VoiceMessageInfo info, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceMessageAsync(data, info, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> sendVoiceMessageAsync(byte[] data, VoiceMessageInfo info)
    {
        return _iceI_sendVoiceMessageAsync(data, info, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> sendVoiceMessageAsync(byte[] data, VoiceMessageInfo info, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceMessageAsync(data, info, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_info -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_sendVoiceMessageAsync(byte[] iceP_data, VoiceMessageInfo iceP_info, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceMessage", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeByteSeq(iceP_data);
                     VoiceMessageInfo.ice_write(ostr, iceP_info);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void initiateCall(String recipient)
    {
        initiateCall(recipient, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void initiateCall(String recipient, java.util.Map<String, String> context)
    {
        _iceI_initiateCallAsync(recipient, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> initiateCallAsync(String recipient)
    {
        return _iceI_initiateCallAsync(recipient, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> initiateCallAsync(String recipient, java.util.Map<String, String> context)
    {
        return _iceI_initiateCallAsync(recipient, context, false);
    }

    /**
     * @hidden
     * @param iceP_recipient -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_initiateCallAsync(String iceP_recipient, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "initiateCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_recipient);
                 }, null);
        return f;
    }

    default void acceptCall(String caller)
    {
        acceptCall(caller, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void acceptCall(String caller, java.util.Map<String, String> context)
    {
        _iceI_acceptCallAsync(caller, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> acceptCallAsync(String caller)
    {
        return _iceI_acceptCallAsync(caller, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> acceptCallAsync(String caller, java.util.Map<String, String> context)
    {
        return _iceI_acceptCallAsync(caller, context, false);
    }

    /**
     * @hidden
     * @param iceP_caller -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_acceptCallAsync(String iceP_caller, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "acceptCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_caller);
                 }, null);
        return f;
    }

    default void rejectCall(String caller)
    {
        rejectCall(caller, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void rejectCall(String caller, java.util.Map<String, String> context)
    {
        _iceI_rejectCallAsync(caller, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> rejectCallAsync(String caller)
    {
        return _iceI_rejectCallAsync(caller, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> rejectCallAsync(String caller, java.util.Map<String, String> context)
    {
        return _iceI_rejectCallAsync(caller, context, false);
    }

    /**
     * @hidden
     * @param iceP_caller -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_rejectCallAsync(String iceP_caller, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rejectCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_caller);
                 }, null);
        return f;
    }

    default void endCall(String participant)
    {
        endCall(participant, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void endCall(String participant, java.util.Map<String, String> context)
    {
        _iceI_endCallAsync(participant, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> endCallAsync(String participant)
    {
        return _iceI_endCallAsync(participant, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> endCallAsync(String participant, java.util.Map<String, String> context)
    {
        return _iceI_endCallAsync(participant, context, false);
    }

    /**
     * @hidden
     * @param iceP_participant -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_endCallAsync(String iceP_participant, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_participant);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static VoiceChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static VoiceChatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static VoiceChatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, VoiceChatPrx.class, _VoiceChatPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default VoiceChatPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (VoiceChatPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default VoiceChatPrx ice_adapterId(String newAdapterId)
    {
        return (VoiceChatPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default VoiceChatPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (VoiceChatPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default VoiceChatPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (VoiceChatPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default VoiceChatPrx ice_invocationTimeout(int newTimeout)
    {
        return (VoiceChatPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default VoiceChatPrx ice_connectionCached(boolean newCache)
    {
        return (VoiceChatPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default VoiceChatPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (VoiceChatPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoiceChatPrx ice_secure(boolean b)
    {
        return (VoiceChatPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default VoiceChatPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (VoiceChatPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default VoiceChatPrx ice_preferSecure(boolean b)
    {
        return (VoiceChatPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default VoiceChatPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (VoiceChatPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default VoiceChatPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (VoiceChatPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default VoiceChatPrx ice_collocationOptimized(boolean b)
    {
        return (VoiceChatPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default VoiceChatPrx ice_twoway()
    {
        return (VoiceChatPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default VoiceChatPrx ice_oneway()
    {
        return (VoiceChatPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default VoiceChatPrx ice_batchOneway()
    {
        return (VoiceChatPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default VoiceChatPrx ice_datagram()
    {
        return (VoiceChatPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default VoiceChatPrx ice_batchDatagram()
    {
        return (VoiceChatPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default VoiceChatPrx ice_compress(boolean co)
    {
        return (VoiceChatPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default VoiceChatPrx ice_timeout(int t)
    {
        return (VoiceChatPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default VoiceChatPrx ice_connectionId(String connectionId)
    {
        return (VoiceChatPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default VoiceChatPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (VoiceChatPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::demo::VoiceChat";
    }
}
